// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuSomGwFE-VpSOwqk9CoaAhqMQ2VwHIHI',
    appId: '1:431161358299:web:99c49470dafca022b519fe',
    messagingSenderId: '431161358299',
    projectId: 'flutter-final-devill',
    authDomain: 'flutter-final-devill.firebaseapp.com',
    storageBucket: 'flutter-final-devill.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz9qb7MLqZ9qm-L_xB-_CEJjrw88SomhE',
    appId: '1:431161358299:android:651a8f0a7a40a720b519fe',
    messagingSenderId: '431161358299',
    projectId: 'flutter-final-devill',
    storageBucket: 'flutter-final-devill.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABLihkQrXJ1feFZ0C9xSn_HX9K-ODTNmQ',
    appId: '1:431161358299:ios:84708439d2ce5d58b519fe',
    messagingSenderId: '431161358299',
    projectId: 'flutter-final-devill',
    storageBucket: 'flutter-final-devill.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABLihkQrXJ1feFZ0C9xSn_HX9K-ODTNmQ',
    appId: '1:431161358299:ios:dffecba0049685a6b519fe',
    messagingSenderId: '431161358299',
    projectId: 'flutter-final-devill',
    storageBucket: 'flutter-final-devill.appspot.com',
    iosBundleId: 'com.example.finalProject.RunnerTests',
  );
}
